version: "3.7"
services:
  cache:
    build:
      target: cache
      context: ./dashboard
      dockerfile: cache.Dockerfile
    volumes:
      - data:/data/
    restart: unless-stopped
  gosst-http:
    build:
      target: gosst-http
      context: ./gosst
    volumes:
      - data:/data/
    restart: unless-stopped
    depends_on:
      - cache
  gosst-tcp:
    build:
      target: gosst-tcp
      context: ./gosst
    ports:
      - "557:557"
    volumes:
      - data:/data/
    restart: unless-stopped
    depends_on:
      - cache
  dashboard:
    build:
      target: dashboard
      context: ./dashboard
      dockerfile: dashboard.Dockerfile
    volumes:
      - data:/data/
    restart: unless-stopped
    depends_on:
      - gosst-http
  caddy:
    image: caddy:2.6.4
    restart: unless-stopped
    depends_on:
      - dashboard
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - data:/data/
volumes:
  data: